// Cross-platform conversion: Cursor, Codex, OpenCode
export interface MissionSpec {
  title: string;
  goal: string;
  done_when: string[];
  constraints?: string[];
}

export function convertToCursor(mission: MissionSpec): string {
  const lines: string[] = [
    `# ${mission.title}`,
    "",
    `## Goal`,
    mission.goal,
    "",
    "## Done When",
  ];
  mission.done_when.forEach((c) => lines.push(`- ${c}`));

  if (mission.constraints && mission.constraints.length > 0) {
    lines.push("", "## Constraints");
    mission.constraints.forEach((c) => lines.push(`- ${c}`));
  }

  return lines.join("\n");
}

export function convertToCodex(mission: MissionSpec): string {
  const lines: string[] = [
    `# ${mission.title}`,
    "",
    mission.goal,
    "",
    "## Checklist",
  ];
  mission.done_when.forEach((c) => lines.push(`- [ ] ${c}`));

  if (mission.constraints && mission.constraints.length > 0) {
    lines.push("", "## Constraints");
    mission.constraints.forEach((c) => lines.push(`- ${c}`));
  }

  return lines.join("\n");
}

function tomlString(value: string): string {
  if (value.includes("\n")) {
    // TOML multiline basic string: quotes are allowed inside without escaping
    return `"""\n${value}"""`;
  }
  // TOML basic string: escape backslashes first, then double quotes
  const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `"${escaped}"`;
}

function tomlArray(arr: string[]): string {
  return `[ ${arr.map((s) => tomlString(s)).join(", ")} ]`;
}

export function convertToOpenCode(mission: MissionSpec): string {
  const lines: string[] = [
    `[mission]`,
    `title = ${tomlString(mission.title)}`,
    `goal = ${tomlString(mission.goal)}`,
    `done_when = ${tomlArray(mission.done_when)}`,
  ];

  if (mission.constraints && mission.constraints.length > 0) {
    lines.push(`constraints = ${tomlArray(mission.constraints)}`);
  }

  return lines.join("\n");
}

// Cline (Cursor-like IDE). The .clinerules convention mirrors .cursorrules —
// a markdown-formatted rules file read by the agent at session start.
export function convertToCline(mission: MissionSpec): string {
  const lines: string[] = [
    `# ${mission.title}`,
    "",
    `## Mission`,
    mission.goal,
    "",
    "## Completion criteria (done_when)",
  ];
  mission.done_when.forEach((c) => lines.push(`- ${c}`));

  if (mission.constraints && mission.constraints.length > 0) {
    lines.push("", "## Constraints");
    mission.constraints.forEach((c) => lines.push(`- ${c}`));
  }

  lines.push(
    "",
    "<!-- Generated by mission-spec. Do not edit by hand; edit mission.yaml and regenerate. -->",
  );
  return lines.join("\n");
}

// Continue (VS Code / JetBrains agent). Uses .continuerules — markdown rules
// file similar in spirit to Cursor/Cline.
export function convertToContinue(mission: MissionSpec): string {
  const lines: string[] = [
    `# ${mission.title}`,
    "",
    "> Continue agent rules — generated from mission.yaml. Do not edit by hand.",
    "",
    "## Goal",
    mission.goal,
    "",
    "## Done-when checklist",
  ];
  mission.done_when.forEach((c) => lines.push(`- [ ] ${c}`));

  if (mission.constraints && mission.constraints.length > 0) {
    lines.push("", "## Constraints");
    mission.constraints.forEach((c) => lines.push(`- ${c}`));
  }
  return lines.join("\n");
}

// Aider. Uses .aider.conf.yml (YAML config). We generate a companion
// .aider-mission.md file elsewhere and reference it via the `read:` list.
// Returns an object so the caller can write both files.
export interface AiderArtifacts {
  conf: string; // .aider.conf.yml content
  context: string; // .aider-mission.md content
  referencedContextPath: string; // the path inside conf that points to context
}

function yamlQuote(value: string): string {
  // Minimal YAML-safe single-line quoting for strings in our output.
  const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `"${escaped}"`;
}

export function convertToAider(mission: MissionSpec): AiderArtifacts {
  const contextLines: string[] = [
    `# ${mission.title}`,
    "",
    "## Goal",
    mission.goal,
    "",
    "## Done When",
  ];
  mission.done_when.forEach((c) => contextLines.push(`- ${c}`));
  if (mission.constraints && mission.constraints.length > 0) {
    contextLines.push("", "## Constraints");
    mission.constraints.forEach((c) => contextLines.push(`- ${c}`));
  }
  const context = contextLines.join("\n");

  const contextPath = ".aider-mission.md";
  const confLines: string[] = [
    "# Generated by mission-spec — do not edit by hand.",
    `# Title: ${yamlQuote(mission.title)}`,
    "read:",
    `  - ${contextPath}`,
    "",
    "# Aider picks up rules from the file listed under `read:` at session start.",
  ];
  return {
    conf: confLines.join("\n"),
    context,
    referencedContextPath: contextPath,
  };
}
