// Architecture Registry 버전 간 diff 생성
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { parse } from "yaml";
import { execFileSync } from "node:child_process";

export interface ArchModule {
  id: string;
  path: string;
  responsibility: string;
  depends_on?: string[];
}

interface ArchRegistry {
  modules?: ArchModule[];
}

export interface ModuleDiff {
  added: ArchModule[];
  removed: ArchModule[];
  changed: Array<{
    id: string;
    field: string;
    from: string;
    to: string;
  }>;
}

export interface DependencyDiff {
  added: Array<{ from: string; to: string }>;
  removed: Array<{ from: string; to: string }>;
}

export interface ArchDiffResult {
  from: string;
  to: string;
  modules: ModuleDiff;
  dependencies: DependencyDiff;
  hasDiff: boolean;
  markdown: string;
}

function parseModules(data: unknown): ArchModule[] {
  const reg = data as ArchRegistry;
  return (reg?.modules ?? []).map((m) => ({
    id: m.id,
    path: m.path,
    responsibility: m.responsibility,
    depends_on: m.depends_on ?? [],
  }));
}

function buildDepEdges(modules: ArchModule[]): Set<string> {
  const edges = new Set<string>();
  for (const m of modules) {
    for (const dep of m.depends_on ?? []) {
      edges.add(`${m.id}->${dep}`);
    }
  }
  return edges;
}

export function diffArchitectures(
  oldData: unknown,
  newData: unknown,
  fromLabel = "old",
  toLabel = "new",
): ArchDiffResult {
  const oldModules = parseModules(oldData);
  const newModules = parseModules(newData);

  const oldMap = new Map(oldModules.map((m) => [m.id, m]));
  const newMap = new Map(newModules.map((m) => [m.id, m]));

  // Module diff
  const added = newModules.filter((m) => !oldMap.has(m.id));
  const removed = oldModules.filter((m) => !newMap.has(m.id));
  const changed: ModuleDiff["changed"] = [];

  for (const [id, newMod] of newMap) {
    const oldMod = oldMap.get(id);
    if (!oldMod) continue;
    if (oldMod.path !== newMod.path) {
      changed.push({ id, field: "path", from: oldMod.path, to: newMod.path });
    }
    if (oldMod.responsibility !== newMod.responsibility) {
      changed.push({
        id,
        field: "responsibility",
        from: oldMod.responsibility,
        to: newMod.responsibility,
      });
    }
    const oldDeps = (oldMod.depends_on ?? []).sort().join(",");
    const newDeps = (newMod.depends_on ?? []).sort().join(",");
    if (oldDeps !== newDeps) {
      changed.push({
        id,
        field: "depends_on",
        from: oldDeps || "(none)",
        to: newDeps || "(none)",
      });
    }
  }

  // Dependency edge diff
  const oldEdges = buildDepEdges(oldModules);
  const newEdges = buildDepEdges(newModules);
  const addedEdges: DependencyDiff["added"] = [];
  const removedEdges: DependencyDiff["removed"] = [];

  for (const edge of newEdges) {
    if (!oldEdges.has(edge)) {
      const [from, to] = edge.split("->");
      addedEdges.push({ from, to });
    }
  }
  for (const edge of oldEdges) {
    if (!newEdges.has(edge)) {
      const [from, to] = edge.split("->");
      removedEdges.push({ from, to });
    }
  }

  const hasDiff =
    added.length > 0 ||
    removed.length > 0 ||
    changed.length > 0 ||
    addedEdges.length > 0 ||
    removedEdges.length > 0;

  // Render markdown
  const lines: string[] = [
    `# Architecture Diff: ${fromLabel} → ${toLabel}`,
    "",
  ];

  if (!hasDiff) {
    lines.push("No changes detected.");
  } else {
    if (added.length > 0) {
      lines.push("## Modules Added", "");
      added.forEach((m) =>
        lines.push(`- **${m.id}** (\`${m.path}\`): ${m.responsibility}`),
      );
      lines.push("");
    }
    if (removed.length > 0) {
      lines.push("## Modules Removed", "");
      removed.forEach((m) =>
        lines.push(`- **${m.id}** (\`${m.path}\`): ${m.responsibility}`),
      );
      lines.push("");
    }
    if (changed.length > 0) {
      lines.push("## Modules Changed", "");
      lines.push("| Module | Field | From | To |");
      lines.push("|---|---|---|---|");
      changed.forEach((c) =>
        lines.push(`| ${c.id} | ${c.field} | ${c.from} | ${c.to} |`),
      );
      lines.push("");
    }
    if (addedEdges.length > 0) {
      lines.push("## Dependencies Added", "");
      addedEdges.forEach((e) => lines.push(`- ${e.from} → ${e.to}`));
      lines.push("");
    }
    if (removedEdges.length > 0) {
      lines.push("## Dependencies Removed", "");
      removedEdges.forEach((e) => lines.push(`- ${e.from} → ${e.to}`));
      lines.push("");
    }
  }

  lines.push(
    "---",
    `*Generated by architecture-diff — ${new Date().toISOString()}*`,
  );

  return {
    from: fromLabel,
    to: toLabel,
    modules: { added, removed, changed },
    dependencies: { added: addedEdges, removed: removedEdges },
    hasDiff,
    markdown: lines.join("\n"),
  };
}

const ARCH_REGISTRY_PATH = ".mission/architecture/ARCHITECTURE_CURRENT.yaml";

export function diffArchitectureFromGit(
  projectDir: string,
  ref = "HEAD~1",
): ArchDiffResult {
  const currentPath = join(projectDir, ARCH_REGISTRY_PATH);
  if (!existsSync(currentPath)) {
    throw new Error(`${ARCH_REGISTRY_PATH} not found in ${projectDir}`);
  }
  const currentData = parse(readFileSync(currentPath, "utf-8"));

  let oldData: unknown = { modules: [] };
  try {
    const oldContent = execFileSync(
      "git",
      ["show", `${ref}:${ARCH_REGISTRY_PATH}`],
      { cwd: projectDir, encoding: "utf-8" },
    );
    oldData = parse(oldContent);
  } catch {
    // ref doesn't have the file — treat as empty (all modules are "added")
  }

  return diffArchitectures(oldData, currentData, ref, "current");
}
